// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/training-studio/BrainMap.tsx": () => import("../components/mockups/training-studio/BrainMap.tsx"),
  "./components/mockups/training-studio/TeachingCockpit.tsx": () => import("../components/mockups/training-studio/TeachingCockpit.tsx"),
  "./components/mockups/training-studio/TrainingTimeline.tsx": () => import("../components/mockups/training-studio/TrainingTimeline.tsx")
};
